databases:
    - name: agrilab
      databaseName: agrilab
      user: agrilab

services:
    - type: web
      name: agrilab
      env: python
      buildCommand: "./build.sh"
      startCommand: "gunicorn agrilab.wsgi:application"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: agrilab
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
